### ISSUE TITLE
ocamlfind: Package `bin_prot.syntax' not found

### ISSUE THREAD

**Issue by vusirikala** [generic-group-analyzer/gga-unbounded#2]
I am trying to install gga-unbouned. I am using mac. I installed eliom, core, bin_prot, lwt packages. When I run my code it shows the following error.
```
$ make
ocamlbuild -pkg core_kernel -tag short_paths -pkg sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -pkg bin_prot.syntax -cflags -strict-sequence -cflags "-w +a-e-9-44-48" -use-menhir -menhir "menhir -v" -classic-display -use-ocamlfind -quiet -ocamlc ocamlc -ocamlopt ocamlopt ./ubt.native
+ ocamlfind ocamldep -package num -package core_kernel -syntax camlp4o -package websocket.lwt -package yojson -package lwt -package lwt.ppx -package uri -package cohttp.lwt -package ppx_deriving.std -package containers -package nocrypto.lwt -package conduit -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -modules src/ubt.ml > src/ubt.ml.depends
ocamlfind: Package `bin_prot.syntax' not found
Command exited with code 2.
make: *** [ubt.native] Error 10
```
When I tried to install bin_prot.syntax, it says
```
$ opam install bin_prot.syntax
[ERROR] No package matches bin_prot.syntax.
```
How should I install .syntax packages? I am using opam stable version 1.2.2.
```
$ opam list | grep bin_prot
bin_prot                           v0.11.0  A binary protocol generator
ppx_bin_prot                       v0.11.0  Generation of bin_prot readers and w
$ opam list | grep core
core                               v0.11.1  Industrial strength alternative to O
core_kernel                        v0.11.0  Industrial strength alternative to O
$ opam list | grep lwt
cstruct-lwt                          3.2.1  Access C-like structures directly fr
js_of_ocaml-lwt                      3.2.0  Compiler from OCaml bytecode to Java
lwt                                  3.3.0  Promises, concurrency, and paralleli
lwt_log                              1.0.0  Lwt logging library (deprecated)
lwt_ppx                              1.2.1  PPX syntax for Lwt, providing someth
lwt_react                            1.1.1  Helpers for using React with Lwt
lwt_ssl                              1.1.2  OpenSSL binding with concurrent I/O
```
I need to use gga unbounded project for my research. Please help me fixing this.

**Comment by miguel-ambrona** [comment]
Hi Vusirikala,
What version of the compiler are you using? You can check it by running _opam switch_.
It should work fine for the version 4.02.3.
The newest version is 4.06.1, for that one, things may be have changed, different package names...

I recommend to create a Switch for installing the 4.02.3 compiler. You will be able to go back to your current compiler in the future:

_opam switch **gga_ub** --alias-of 4.02.3_

There  you can replace "gga_ub" with a different name of your choice.
You will probably need to run _eval `opam config env`_ after the installation.

Once you have the version 4.02.3 you can install all packages at once with the following two commands:

_opam pin add gga-unbounded **FOLDER** -n_
_opam install gga-unbounded --deps-only_

Where in FOLDER you should write the path to the folder where you cloned the repository.

Please, let me know if that fixes your problem and if you have other questions.

I also recommend to look at this webpage:
https://generic-group-analyzer.github.io/gga-ub/

**Comment by vusirikala** [comment]
Thanks a lot Miguel. I tried switching back to ocaml version 4.02.3. When I ran the commands, it installed core_kernel.113.33.0 package which is the newer version. I got some errors as a result. I tried to downgrade it to core_kernel.113.24.0. It installed most of the dependencies but not ppx_expect.113.24.0. I removed opam and then reinstalled everything from scratch. It still shows the same error. Please help me fixing this. 
```
$ opam install core_kernel.113.24.0
The following actions will be performed:
  ∗  install ppx_expect  113.24.00            [required by core_kernel]
  ∗  install ppx_jane    113.24.01            [required by core_kernel]
  ∗  install core_kernel 113.24.00
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[core_kernel] Archive in cache
[ppx_expect] Archive in cache
[ppx_jane] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of ppx_expect failed at "make".

#=== ERROR while installing ppx_expect.113.24.00 ==============================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/satya/.opam/gga_ub/build/ppx_expect.113.24.00
# compiler     4.02.3
# exit-code    2
# env-file     /Users/satya/.opam/gga_ub/build/ppx_expect.113.24.00/ppx_expect-96557-e7966f.env
# stdout-file  /Users/satya/.opam/gga_ub/build/ppx_expect.113.24.00/ppx_expect-96557-e7966f.out
# stderr-file  /Users/satya/.opam/gga_ub/build/ppx_expect.113.24.00/ppx_expect-96557-e7966f.err
### stdout ###
# [...]
# /Users/satya/.opam/gga_ub/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I collector -package variantslib -package sexplib -package re -package ppx_inline_test.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -pp './ppx-driver-ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv.native -dump-ast -inline-test-lib ppx_expect.evaluator' -predicates ppx_driver -w -40 -I evaluator/lib -I collector -I namespace_wrappers -o evaluator/lib/evaluator.cmo evaluator/lib/evaluator.ml
# /Users/satya/.opam/gga_ub/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I collector -package variantslib -package sexplib -package re -package ppx_inline_test.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -pp './ppx-driver-ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv.native -dump-ast -inline-test-lib ppx_expect.evaluator' -predicates ppx_driver -w -40 -I evaluator/lib -I collector -I namespace_wrappers -o evaluator/lib/expectation.cmo evaluator/lib/expectation.ml
# /Users/satya/.opam/gga_ub/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I collector -package variantslib -package sexplib -package re -package ppx_inline_test.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -pp './ppx-driver-ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv.native -dump-ast -inline-test-lib ppx_expect.evaluator' -predicates ppx_driver -w -40 -I evaluator/lib -I collector -I namespace_wrappers -o evaluator/lib/lexer.cmo evaluator/lib/lexer.ml
# /Users/satya/.opam/gga_ub/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I collector -package variantslib -package sexplib -package re -package ppx_inline_test.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -pp './ppx-driver-ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv.native -dump-ast -inline-test-lib ppx_expect.evaluator' -predicates ppx_driver -w -40 -I evaluator/lib -I collector -I namespace_wrappers -o evaluator/lib/reconcile.cmo evaluator/lib/reconcile.ml
# + /Users/satya/.opam/gga_ub/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I collector -package variantslib -package sexplib -package re -package ppx_inline_test.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -pp './ppx-driver-ppx_assert+ppx_compare+ppx_custom_printf+ppx_inline_test+ppx_sexp_conv+ppx_variants_conv.native -dump-ast -inline-test-lib ppx_expect.evaluator' -predicates ppx_driver -w -40 -I evaluator/lib -I collector -I namespace_wrappers -o evaluator/lib/reconcile.cmo evaluator/lib/reconcile.ml
# File "evaluator/lib/reconcile.ml", line 62, characters 25-36:
# Error: Unbound value Re_emacs.re
# Command exited with code 2.
# + ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package ppx_driver.ocamlbuild myocamlbuild.ml /Users/satya/.opam/gga_ub/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /Users/satya/.opam/gga_ub/lib/ocaml/compiler-libs, /Users/satya/.opam/gga_ub/lib/ocaml
### stderr ###
# W: Cannot find source file matching module 'ppx_expect' in library ppx_expect
# W: Cannot find source file matching module 'expect_test_evaluator_lib' in library expect_test_evaluator_lib
# E: Failure("Command ''/Users/satya/.opam/gga_ub/bin/ocamlbuild' collector/expect_test_collector.cma collector/expect_test_collector.cmxa collector/expect_test_collector.a collector/expect_test_collector.cmxs evaluator/lib/libexpect_test_evaluator_lib_stubs.a evaluator/lib/dllexpect_test_evaluator_lib_stubs.so evaluator/lib/expect_test_evaluator_lib.cma evaluator/lib/expect_test_evaluator_lib.cmxa evaluator/lib/expect_test_evaluator_lib.a evaluator/lib/expect_test_evaluator_lib.cmxs src/ppx_expect.cma src/ppx_expect.cmxa src/ppx_expect.a src/ppx_expect.cmxs as_ppx/ppx.native -use-ocamlfind -plugin-tags 'package(ppx_driver.ocamlbuild)' -tag debug' terminated with error code 10")
# make: *** [build] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install core_kernel 113.24.00
  ∗  install ppx_jane    113.24.01
The following actions failed
  ∗  install ppx_expect 113.24.00
No changes have been performed
```

**Comment by miguel-ambrona** [comment]
Hi Sayta,
I am sorry you are having so many troubles...
I am not very familiar with macOS. But let's see if we can fix it.

I would try to install core version 113.00.00 instead, maybe that solves your problem.
Just in case, here you are a list of all packages that I have installed in my compiler:

`base-bigarray          base  Bigarray library distributed with the OCaml compile
base-bytes             base  Bytes library distributed with the OCaml compiler
base-ocamlbuild        base  OCamlbuild binary and libraries distributed with th
base-threads           base  Threads library distributed with the OCaml compiler
base-unix              base  Unix library distributed with the OCaml compiler
base64                2.0.0  Base64 encoding and decoding library
bin_prot          113.00.00  A binary protocol generator
biniou               1.0.12  Binary data format designed for speed, safety, ease
camlp4               4.02+7  Camlp4 is a system for writing extensible parsers f
cmdliner              0.9.8  Declarative definition of command line interfaces f
cohttp               0.18.3  HTTP library for Lwt, Async and Mirage
comparelib        113.00.00  Part of Jane Street’s Core library
conduit               0.9.0  Network connection library for TCP and SSL
conf-gmp                  1  Virtual package relying on a GMP lib system install
conf-m4                   1  Virtual package relying on m4
conf-ncurses              1  Virtual package relying on ncurses
conf-openssl              1  Virtual package relying on an OpenSSL system instal
conf-perl                 1  Virtual package relying on perl
conf-pkg-config         1.0  Virtual package relying on pkg-config installation.
conf-which                1  Virtual package relying on which
conf-zlib                 1  Virtual package relying on zlib
containers             0.18  A modular extension of the OCaml standard library w
core_kernel       113.00.00  Industrial strength alternative to OCaml's standard
cppo                  1.3.2  Equivalent of the C preprocessor for OCaml programs
cryptokit              1.10  Cryptographic primitives library. 
cstruct               2.2.0  access C structures via a camlp4 extension
ctypes                0.4.1  Combinators for binding to C libraries without writ
ctypes-foreign        0.4.0  Virtual package for enabling the ctypes.foreign sub
custom_printf     113.00.00  Extension for printf format strings
easy-format           1.2.0  High-level and functional interface to the Format m
enumerate         111.08.00  Quotation expanders for enumerating finite types.
fieldslib         113.00.00  Syntax extension to define first class values repre
herelib           112.35.00  Part of Jane Street’s Core library
ipaddr                2.6.1  IP (and MAC) address representation library
lwt                   2.4.8  A cooperative threads library for OCaml
magic-mime            1.0.0  Convert file extensions to MIME types
menhir             20160526  LR(1) parser generator
mirage-no-xen             1  Virtual package conflicting with mirage-xen
nocrypto              0.5.2  Small functional-style crypto library.
ocamlbuild                0  Build system distributed with the OCaml compiler si
ocamlfind             1.6.2  A library manager for OCaml
ocplib-endian           1.0  Optimised functions to read and write int16/32/64 f
optcomp                 1.6  Optional compilation with cpp-like directives
ounit                 2.0.0  Unit testing framework loosely based on HUnit. It i
pa_bench          113.00.00  Syntax extension for inline benchmarks
pa_ounit          113.00.00  Syntax extension for oUnit
pa_test           112.24.00  Quotation expander for assertions.
pipebang          113.00.00  Part of Jane Street’s Core library
ppx_deriving            4.0  Type-driven code generation for OCaml >=4.02
ppx_tools        5.0+4.02.0  Tools for authors of ppx rewriters and other syntac
re                    1.6.1  RE is a regular expression library for OCaml
result                  1.2  Compatibility Result module
sexplib           113.00.00  Library for serializing OCaml values to and from S-
ssl                   0.5.2  Bindings for OpenSSL
stringext             1.4.2  Extra string functions for OCaml
type_conv         113.00.02  Library for building type-driven syntax extensions
typerep           113.00.00  typerep is a library for runtime types.
uri                   1.9.1  RFC3986 URI/URL parsing library
variantslib       109.15.03  Part of Jane Street’s Core library
websocket               2.1  Websocket library
yojson                1.3.2  Yojson is an optimized parsing and printing library
zarith                1.4.1  Implements arithmetic and logical operations over a`

You don't need to install them all, only those listed by the --deps-only command. But the above list can help you to know the versions of packages that will make things work.

By the way, if you want to check your own list, run `opam list`.

Let me know if you succeed!

**Comment by miguel-ambrona** [comment]
Hi Sayta,
I am sorry you are having so many troubles...
I am not very familiar with macOS. But let's see if we can fix it.

I would try to install core version 113.00.00 instead, maybe that solves your problem.
Just in case, here you are a list of all packages that I have installed in my compiler:

```
base-bigarray          base  Bigarray library distributed with the OCaml compile
base-bytes             base  Bytes library distributed with the OCaml compiler
base-ocamlbuild        base  OCamlbuild binary and libraries distributed with th
base-threads           base  Threads library distributed with the OCaml compiler
base-unix              base  Unix library distributed with the OCaml compiler
base64                2.0.0  Base64 encoding and decoding library
bin_prot          113.00.00  A binary protocol generator
biniou               1.0.12  Binary data format designed for speed, safety, ease
camlp4               4.02+7  Camlp4 is a system for writing extensible parsers f
cmdliner              0.9.8  Declarative definition of command line interfaces f
cohttp               0.18.3  HTTP library for Lwt, Async and Mirage
comparelib        113.00.00  Part of Jane Street’s Core library
conduit               0.9.0  Network connection library for TCP and SSL
conf-gmp                  1  Virtual package relying on a GMP lib system install
conf-m4                   1  Virtual package relying on m4
conf-ncurses              1  Virtual package relying on ncurses
conf-openssl              1  Virtual package relying on an OpenSSL system instal
conf-perl                 1  Virtual package relying on perl
conf-pkg-config         1.0  Virtual package relying on pkg-config installation.
conf-which                1  Virtual package relying on which
conf-zlib                 1  Virtual package relying on zlib
containers             0.18  A modular extension of the OCaml standard library w
core_kernel       113.00.00  Industrial strength alternative to OCaml's standard
cppo                  1.3.2  Equivalent of the C preprocessor for OCaml programs
cryptokit              1.10  Cryptographic primitives library. 
cstruct               2.2.0  access C structures via a camlp4 extension
ctypes                0.4.1  Combinators for binding to C libraries without writ
ctypes-foreign        0.4.0  Virtual package for enabling the ctypes.foreign sub
custom_printf     113.00.00  Extension for printf format strings
easy-format           1.2.0  High-level and functional interface to the Format m
enumerate         111.08.00  Quotation expanders for enumerating finite types.
fieldslib         113.00.00  Syntax extension to define first class values repre
herelib           112.35.00  Part of Jane Street’s Core library
ipaddr                2.6.1  IP (and MAC) address representation library
lwt                   2.4.8  A cooperative threads library for OCaml
magic-mime            1.0.0  Convert file extensions to MIME types
menhir             20160526  LR(1) parser generator
mirage-no-xen             1  Virtual package conflicting with mirage-xen
nocrypto              0.5.2  Small functional-style crypto library.
ocamlbuild                0  Build system distributed with the OCaml compiler si
ocamlfind             1.6.2  A library manager for OCaml
ocplib-endian           1.0  Optimised functions to read and write int16/32/64 f
optcomp                 1.6  Optional compilation with cpp-like directives
ounit                 2.0.0  Unit testing framework loosely based on HUnit. It i
pa_bench          113.00.00  Syntax extension for inline benchmarks
pa_ounit          113.00.00  Syntax extension for oUnit
pa_test           112.24.00  Quotation expander for assertions.
pipebang          113.00.00  Part of Jane Street’s Core library
ppx_deriving            4.0  Type-driven code generation for OCaml >=4.02
ppx_tools        5.0+4.02.0  Tools for authors of ppx rewriters and other syntac
re                    1.6.1  RE is a regular expression library for OCaml
result                  1.2  Compatibility Result module
sexplib           113.00.00  Library for serializing OCaml values to and from S-
ssl                   0.5.2  Bindings for OpenSSL
stringext             1.4.2  Extra string functions for OCaml
type_conv         113.00.02  Library for building type-driven syntax extensions
typerep           113.00.00  typerep is a library for runtime types.
uri                   1.9.1  RFC3986 URI/URL parsing library
variantslib       109.15.03  Part of Jane Street’s Core library
websocket               2.1  Websocket library
yojson                1.3.2  Yojson is an optimized parsing and printing library
zarith                1.4.1  Implements arithmetic and logical operations over a
```

You don't need to install them all, only those listed by the --deps-only command. But the above list can help you to know the versions of packages that will make things work.

By the way, if you want to check your own list, run `opam list`.

Let me know if you succeed!

**Comment by vusirikala** [comment]
Thanks a lot Miguele for the list. I installed lower version of "re" package and it finally worked!

**Comment by miguel-ambrona** [comment]
Great!
By the way, I created this website to give more explanations about the tool:
https://generic-group-analyzer.github.io/gga-ub/index.html

And I also recommend using the previous tool:
https://github.com/generic-group-analyzer/gga

It does not provide the same guarantees of security, but it is better for finding attacks. You should play with gga until you get a good candidate (for which no attack exists with a small number of queries) and then try to go for the gga-unbounded to prove better security.

I believe there are a few differences in the input file syntax between the two tools. But it should not be too much.

**Comment by vusirikala** [comment]
Thanks a lot for the information :)
